FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /app

COPY *.sln */*.csproj ./
RUN perl -e 'foreach(@ARGV){/(.*).csproj/;mkdir($1);rename($&,"$1/$&")}' *.csproj
RUN dotnet restore

COPY . .
RUN dotnet build --no-restore -c Release
RUN dotnet publish --no-restore --no-dependencies -c Release -o ../out Fantabulous.Api.User/*.csproj

FROM microsoft/aspnetcore:2.0
WORKDIR /app

COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "Fantabulous.Api.User.dll"]
